package modelo.dto;
// Generated 06-dic-2018 13:18:24 by Hibernate Tools 4.3.1



/**
 * Boleta generated by hbm2java
 */
public class Boleta  implements java.io.Serializable {


     private Integer idBoleta;
     private Compra compra;
     private Estacionamiento estacionamiento;
     private int cantidad;
     private int montoBoleta;

    public Boleta() {
    }

    public Boleta(Compra compra, Estacionamiento estacionamiento, int cantidad, int montoBoleta) {
       this.compra = compra;
       this.estacionamiento = estacionamiento;
       this.cantidad = cantidad;
       this.montoBoleta = montoBoleta;
    }
   
    public Integer getIdBoleta() {
        return this.idBoleta;
    }
    
    public void setIdBoleta(Integer idBoleta) {
        this.idBoleta = idBoleta;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Estacionamiento getEstacionamiento() {
        return this.estacionamiento;
    }
    
    public void setEstacionamiento(Estacionamiento estacionamiento) {
        this.estacionamiento = estacionamiento;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public int getMontoBoleta() {
        return this.montoBoleta;
    }
    
    public void setMontoBoleta(int montoBoleta) {
        this.montoBoleta = montoBoleta;
    }




}


