package modelo.dto;
// Generated 06-12-2018 23:41:35 by Hibernate Tools 4.3.1



/**
 * Boleta generated by hbm2java
 */
public class Boleta  implements java.io.Serializable {


     private Integer idBoleta;
     private Compra compra;
     private Estacionamiento estacionamiento;
     private Integer cantidad;
     private Integer montoBoleta;

    public Boleta() {
    }

    public Boleta(Compra compra, Estacionamiento estacionamiento, Integer cantidad, Integer montoBoleta) {
       this.compra = compra;
       this.estacionamiento = estacionamiento;
       this.cantidad = cantidad;
       this.montoBoleta = montoBoleta;
    }
   
    public Integer getIdBoleta() {
        return this.idBoleta;
    }
    
    public void setIdBoleta(Integer idBoleta) {
        this.idBoleta = idBoleta;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Estacionamiento getEstacionamiento() {
        return this.estacionamiento;
    }
    
    public void setEstacionamiento(Estacionamiento estacionamiento) {
        this.estacionamiento = estacionamiento;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Integer getMontoBoleta() {
        return this.montoBoleta;
    }
    
    public void setMontoBoleta(Integer montoBoleta) {
        this.montoBoleta = montoBoleta;
    }




}


