package modelo.dto;
// Generated 06-dic-2018 13:18:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private Integer idCompra;
     private Cliente cliente;
     private int montoTotal;
     private boolean pagado;
     private int medioPago;
     private int medioEnvio;
     private Set<Boleta> boletas = new HashSet<Boleta>(0);

    public Compra() {
    }

	
    public Compra(Cliente cliente, int montoTotal, boolean pagado, int medioPago, int medioEnvio) {
        this.cliente = cliente;
        this.montoTotal = montoTotal;
        this.pagado = pagado;
        this.medioPago = medioPago;
        this.medioEnvio = medioEnvio;
    }
    public Compra(Cliente cliente, int montoTotal, boolean pagado, int medioPago, int medioEnvio, Set<Boleta> boletas) {
       this.cliente = cliente;
       this.montoTotal = montoTotal;
       this.pagado = pagado;
       this.medioPago = medioPago;
       this.medioEnvio = medioEnvio;
       this.boletas = boletas;
    }
   
    public Integer getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(Integer idCompra) {
        this.idCompra = idCompra;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public int getMontoTotal() {
        return this.montoTotal;
    }
    
    public void setMontoTotal(int montoTotal) {
        this.montoTotal = montoTotal;
    }
    public boolean isPagado() {
        return this.pagado;
    }
    
    public void setPagado(boolean pagado) {
        this.pagado = pagado;
    }
    public int getMedioPago() {
        return this.medioPago;
    }
    
    public void setMedioPago(int medioPago) {
        this.medioPago = medioPago;
    }
    public int getMedioEnvio() {
        return this.medioEnvio;
    }
    
    public void setMedioEnvio(int medioEnvio) {
        this.medioEnvio = medioEnvio;
    }
    public Set<Boleta> getBoletas() {
        return this.boletas;
    }
    
    public void setBoletas(Set<Boleta> boletas) {
        this.boletas = boletas;
    }




}


