package modelo.dto;
// Generated 06-dic-2018 13:18:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipousuario generated by hbm2java
 */
public class Tipousuario  implements java.io.Serializable {


     private Integer idTipousu;
     private String descripcionUsu;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Tipousuario() {
    }
    
    public Tipousuario(Integer idTipo) {
        this.idTipousu = idTipo;
    }
	
    public Tipousuario(String descripcionUsu) {
        this.descripcionUsu = descripcionUsu;
    }
    public Tipousuario(String descripcionUsu, Set<Usuario> usuarios) {
       this.descripcionUsu = descripcionUsu;
       this.usuarios = usuarios;
    }
   
    public Integer getIdTipousu() {
        return this.idTipousu;
    }
    
    public void setIdTipousu(Integer idTipousu) {
        this.idTipousu = idTipousu;
    }
    public String getDescripcionUsu() {
        return this.descripcionUsu;
    }
    
    public void setDescripcionUsu(String descripcionUsu) {
        this.descripcionUsu = descripcionUsu;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


