package modelo.dto;
// Generated 06-12-2018 23:41:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipousuario generated by hbm2java
 */
public class Tipousuario  implements java.io.Serializable {


     private Integer idTipo;
     private String descripcionTipo;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Tipousuario() {
    }

    public Tipousuario(String descripcionTipo, Set<Usuario> usuarios) {
       this.descripcionTipo = descripcionTipo;
       this.usuarios = usuarios;
    }
   
    public Integer getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(Integer idTipo) {
        this.idTipo = idTipo;
    }
    public String getDescripcionTipo() {
        return this.descripcionTipo;
    }
    
    public void setDescripcionTipo(String descripcionTipo) {
        this.descripcionTipo = descripcionTipo;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


