package modelo.dto;
// Generated 06-dic-2018 13:18:24 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Tipousuario tipousuario;
     private String user;
     private String pass;
     private String nombre;
     private String apellido;
     private int telefono;
     private String correo;
     private Cliente cliente;

    public Usuario() {
    }


    public Usuario(Tipousuario tipousuario, String user, String pass){
        this.tipousuario = tipousuario;
        this.user = user;
        this.pass = pass;
    }
    
    public Usuario(Tipousuario tipousuario, String user, String pass, String nombre, String apellido, int telefono, String correo) {
        this.tipousuario = tipousuario;
        this.user = user;
        this.pass = pass;
        this.nombre = nombre;
        this.apellido = apellido;
        this.telefono = telefono;
        this.correo = correo;
    }
    public Usuario(Tipousuario tipousuario, String user, String pass, String nombre, String apellido, int telefono, String correo, Cliente cliente) {
       this.tipousuario = tipousuario;
       this.user = user;
       this.pass = pass;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.correo = correo;
       this.cliente = cliente;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Tipousuario getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(Tipousuario tipousuario) {
        this.tipousuario = tipousuario;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }




}


